---
title: "stl_lead_inequity.qmd"
author: "Andre Dextre"
format: html
editor: visual
execute: 
  echo: true
  warning: false
---

```{r}
library(tidyverse)
library(janitor)
library(here)
library(skimr)
```

```{r}
stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv")) %>%
  clean_names()
```

```{r}
stl_lead_prop <- stl_lead %>% mutate(prop_white = (white/total_pop) * 100) 
```

```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop,
                              aes(x = pct_elevated,
                                  y = prop_white)) +
  geom_point(aes(color = white),
                 size = 4,
                 alpha = 0.7) +
  theme_light() +
  labs(x = "PCT Elevated",
       y = "White")

stl_lead_plot

```


```{r}
ggsave(plot = stl_lead_plot,
       here("figs", "stl_lead_plot.png"),
       width = 6,
       height = 5)
```

This plot illustrate the pct levels within blood on a white population. 

```{r}
pct_elevated_plot <- ggplot(data = stl_lead_prop,aes(x = pct_elevated)) +
  geom_histogram(color = "white", fill = "dodgerblue")
                     
pct_elevated_plot


```

```{r}
ggsave(plot = pct_elevated_plot,
       here("figs", "elevated_plot.jpg"),
       width = 6,
       height = 5)
```

